---
- hosts: mesos-master-nodes
  sudo: true
  remote_user: vagrant
  tasks:
    - include: install-java-package.yml
    - include: install-mesos-package.yml
    - include: install-zookeeper-package.yml
