- name: Check whether java package is already installed
  command: dpkg-query -W oracle-java7-installer  
  register: java_check_db
  failed_when: java_check_db.rc > 1
  changed_when: java_check_db.rc == 1
- name: Add Java repository to sources
  action: apt_repository repo='ppa:webupd8team/java' 
  when: java_check_db.rc == 1
- name: Autoaccept license for Java
  action: shell echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
  when: java_check_db.rc == 1
- name: Update APT package cache
  action: apt update_cache=yes
  when: java_check_db.rc == 1
- name: Install Java 7
  action: apt pkg=oracle-java7-installer state=latest install_recommends=yes
  when: java_check_db.rc == 1
- name: Set Java 7 Env
  action: apt pkg=oracle-java7-set-default state=latest install_recommends=yes
  when: java_check_db.rc == 1
