---
  - name: installing mandatory OS packages
    apt:
      name=software-properties-common
      state=present

  - name: adding SignalFX apt-repository
    apt_repository:
      repo='ppa:signalfx/collectd-release'

  - name: install package
    become: true
    apt:
      name=collectd
      state=present
      update_cache=yes

  - name: setting up {{ managed_config_dir }} config dir
    become: true
    file:
      path={{ managed_config_dir }}
      state=directory

   # TODO try to avoid this task repetitions using -with-items

  - name: setting up {{ filtering_config_dir }} config dir
    become: true
    file:
      path={{ filtering_config_dir }}
      state=directory

  - name: placing filtering configuration
    become: true
    copy:
      src=filtering.conf
      dest={{ filtering_config_dir }}/filtering.conf

  - name: placing CPU aggregation file
    become: true
    copy:
      src=10-aggregation-cpu.conf
      dest={{ managed_config_dir }}/10-aggregation-cpu.conf